[platformio]
default_envs = boardRemote

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

# Shrink patrition size, usable for update via web app
board_build.partitions = min_spiffs.csv

# Controller
[env:boardController]
upload_port = COM13
monitor_port = COM13
build_flags = 
    -D BOARD_ID=1
build_src_filter = +<main.cpp> +<board_controller.cpp> +<communication.cpp> +<globals.cpp> +<storage.cpp> +<utils.cpp> +<web_server.cpp> +<log.cpp>
lib_deps =
    olikraus/U8g2@^2.35.8
    adafruit/Adafruit INA219@^1.2.0

# Remote
[env:boardRemote]
upload_port = COM6
monitor_port = COM6
build_flags = -D BOARD_ID=2
build_src_filter = +<main.cpp> +<board_remote.cpp> +<communication.cpp> +<globals.cpp> +<storage.cpp> +<utils.cpp> +<web_server.cpp> +<log.cpp>
lib_deps =
    olikraus/U8g2@^2.35.8